FROM alpine:3.14
LABEL Maintainer="Stanislav Khromov <stanislav+github@khromov.se>" \
      Description="Lightweight container with Nginx 1.18 & PHP-FPM 8 based on Alpine Linux."

ARG PHP_VERSION="7.4.26-r0"

# https://github.com/wp-cli/wp-cli/issues/3840
ENV PAGER="more"

# Install packages and remove default server definition
RUN apk --no-cache add curl \
    php7=${PHP_VERSION} \
    php7-ctype \
    php7-mcrypt \
    php7-curl \
    php7-dom \
    php7-exif \
    php7-fileinfo \
    php7-fpm \
    php7-gd \
    php7-iconv \
    php7-intl \
    php7-mbstring \
    php7-mysqli \
    php7-opcache \
    php7-openssl \
    php7-pecl-imagick \
    php7-pecl-redis \
    php7-phar \
    php7-session \
    php7-simplexml \
    php7-soap \
    php7-xml \
    php7-xmlreader \
    php7-zip \
    php7-zlib \
    php7-pdo \
    php7-xmlwriter \
    php7-tokenizer \
    php7-pdo_mysql \
    php7-sockets \
    nginx supervisor tzdata htop mysql-client dcron nano

# Symlink php7 => php
#RUN ln -s /usr/bin/php7 /usr/bin/php

# Install PHP tools
RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar && chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && php composer-setup.php --install-dir=/usr/local/bin --filename=composer

# Configure nginx
COPY config/nginx.conf /etc/nginx/nginx.conf
COPY config/localhost7.conf /etc/nginx/localhost.conf

# Configure PHP-FPM
COPY config/fpm-pool.conf /etc/php7/php-fpm.d/www.conf
COPY config/php.ini /etc/php7/conf.d/custom.ini

# Configure supervisord
COPY config/supervisord--web7.conf /etc/supervisor/conf.d/supervisord.conf

# Setup document root
RUN mkdir -p /var/www/ROOT

# Setup nobody home
RUN mkdir -p /var/www/nobody

# Make sure files/folders needed by the processes are accessable when they run under the nobody user
RUN chown -R nobody.nobody /var/www/ROOT && \
  chown -R nobody.nobody /var/www/nobody && \
  chown -R nobody.nobody /run && \
  chown -R nobody.nobody /var/lib/nginx && \
  chown -R nobody.nobody /var/log/nginx

# Switch to use a non-root user from here on
USER nobody

# Add application
WORKDIR /var/www/ROOT
COPY --chown=nobody src/ /var/www/ROOT/

# Expose the port nginx is reachable on
EXPOSE 8107

# Let supervisord start nginx & php-fpm
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

# Configure a healthcheck to validate that everything is up&running
HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:8107/fpm-ping
