version: "3.3"

services:
  web:
    # container_name: php8
    depends_on:
      - db
    volumes:
      - ~/Sites:/data01/sites
      - ./bin:/data01/bin
      - ./sites-available:/data01/nginx/sites-available
    build: .
    ports:
      - "8080:8080"
    environment:
      FOO: bar
  db:
    image: mysql:8
    ports:
      - "8089:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: app
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
  pma:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: app
      PMA_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
